/// Flutter icons OrderIt
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  OrderIt
///      fonts:
///       - asset: fonts/OrderIt.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class OrderIt {
  OrderIt._();

  static const _kFontFam = 'OrderIt';
  static const String? _kFontPkg = null;

  static const IconData dashboard = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData money_send = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData logout = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData naira = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cart_menu = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shop_1 = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wallet = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData soup = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
